name: GitHub Webhook Trigger

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        
    - name: Trigger Lambda Function
      env:
        LAMBDA_FUNCTION_ARN: ${{ secrets.LAMBDA_FUNCTION_ARN }}
      run: |
        aws lambda invoke \
          --function-name $LAMBDA_FUNCTION_ARN \
          --invocation-type Event \
          --payload '{}' \
          response.json
