name: GitHub Webhook Trigger
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send pull request payload to Lambda
      run: |
        LAMBDA_URL=${{ secrets.LAMBDA_FUNCTION_URL }}
        curl -X POST $LAMBDA_URL \
        -H "Content-Type: application/json" \
        -d '${{ toJson(github.event) }}'

