name: pull request merge POST to AWS

on:
  pull_request:
    types: [merged]

jobs:
  send_post_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  eu-north-1
      - name: Trigger Lambda
        uses: actions/aws-lambda@v2
        with:
          lambda-function-name: pull_request_changes_log
          payload: ${{ toJson(github.event) }}
